### ISSUE TITLE
Server De-sync Disconnect when placing companion 

### ISSUE THREAD

**Issue by JoelHer** [Klonan/Companion_Drones#10]
When placing a drone, and you are in range you get disconnected from the server because of de-sync

https://user-images.githubusercontent.com/73959649/219967898-b81edb03-8994-4541-b565-7a724e3c765f.mp4

[message.txt](https://github.com/Klonan/Companion_Drones/files/10777638/message.txt)

**Comment by JoelHer** [comment]
I also noticed, that this only happens when the companion does not have fuel

**Comment by Klonan** [comment]
I am not sure, the mod has been the same for 2 years and no other desyncs have been reported, so it seem suspect that also you are in a MP scenario.

**Comment by Klonan** [comment]
Nevermind, I looked into it and you are right, it was related to the fueling items
